workflows:
  android_debug:
    name: Android Debug (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.19.0      # lock Node to avoid surprises
    scripts:
      - name: Install deps
        script: |
          npm ci
      - name: Capacitor sync
        script: |
          npx cap add android || true
          npx cap sync android
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
